name:                pcf
version:             0.1.0.0
github:              "githubuser/pcf"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/pcf#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- bytestring
- mtl
- parsec
- text
- haskeline
- repline
- hspec
- tasty
- tasty-golden


library:
  source-dirs: src

executables:
  pcf:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pcf

tests:
  test:
    main:                Main.hs
    source-dirs:         test/Spec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pcf
    - hspec
  test-golden:
     main:               Main.hs
     source-dirs:        test/Golden
     dependencies:
     - pcf
     - tasty
     - tasty-golden
     - bytestring
